version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly

  - package-ecosystem: pub
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
