name: revanced_manager
description: The official ReVanced Manager.
homepage: https://github.com/revanced/revanced-manager

publish_to: 'none'

version: 0.0.26+26

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animations: ^2.0.4
  app_installer: ^1.1.0
  collection: ^1.16.0
  cross_connectivity: ^3.0.5
  device_apps:
    git:
      url: https://github.com/ponces/flutter_plugin_device_apps
      ref: revanced-manager
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  dio_http_cache_lts: ^0.4.1
  dynamic_color: ^1.5.4
  dynamic_themes: ^1.1.0
  expandable: ^5.0.1
  file_picker:
    git:
      url: https://github.com/alexmercerind/flutter_file_picker
      ref: master
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_background: ^1.1.0
  flutter_cache_manager: ^3.3.0
  flutter_i18n: ^0.32.4
  flutter_local_notifications: ^9.8.0+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logcat:
    git:
      url: https://github.com/SuaMusica/logcat
      ref: feature/nullSafe
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pull_to_refresh: ^2.0.0
  root:
    git:
      url: https://github.com/gokul1630/root
      ref: main
  share_extend: ^2.0.0
  shared_preferences: ^2.0.15
  skeletons: ^0.0.3
  stacked: ^3.0.0
  stacked_generator: ^0.8.0
  stacked_services: ^0.9.3
  stacked_themes: ^0.3.9
  timeago: ^3.2.2
  timezone: ^0.8.0
  url_launcher: ^6.1.5
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
