name: revanced_manager
description: An unofficial ReVanced Manager based on Flutter.
homepage: https://github.com/Aunali321/revanced-manager

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animations: ^2.0.4
  app_installer: ^1.1.0
  cupertino_icons: ^1.0.2
  device_apps:
    git:
      url: https://github.com/ponces/flutter_plugin_device_apps
      ref: appinfo-from-storage
  device_info_plus: ^4.1.2
  dynamic_color: ^1.5.4
  dynamic_themes: ^1.1.0
  expandable: ^5.0.1
  file_picker: ^5.0.1
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_background: ^1.1.0
  flutter_cache_manager: ^3.3.0
  flutter_i18n: ^0.32.4
  flutter_local_notifications: ^9.8.0+1
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  github: ^9.4.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  root: ^2.0.2
  share_extend: ^2.0.0
  shared_preferences: ^2.0.15
  skeletons: ^0.0.3
  stacked: ^2.3.15
  stacked_generator: ^0.7.14
  stacked_services: ^0.9.3
  stacked_themes: ^0.3.9
  timeago: ^3.2.2
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
