name: revanced_manager
description: The official ReVanced Manager.
homepage: https://github.com/revanced/revanced-manager

publish_to: 'none'

version: 1.1.0+100100000

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animations: ^2.0.7
  app_installer: ^1.1.0
  collection: ^1.17.0
  cross_connectivity: ^3.0.5
  cr_file_saver:
    git:
      url: https://github.com/dhruvanbhalara/cr_file_saver.git
      ref: a08326ecb48f581b4b09e2e2665d31ed1704c7af
  device_apps:
    git:
      url: https://github.com/ponces/flutter_plugin_device_apps
      ref: revanced-manager
  device_info_plus: ^8.1.0
  dynamic_color: ^1.6.3
  dio: ^5.0.0
  dynamic_themes: ^1.1.0
  expandable: ^5.0.1
  file_picker:
    git:
      url: https://github.com/alexmercerind/flutter_file_picker
      ref: master
  flex_color_scheme: ^7.0.1
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_cache_manager: ^3.3.0
  flutter_i18n: ^0.32.4
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  get_it: 7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logcat:
    git:
      url: https://github.com/SuaMusica/logcat
      ref: feature/nullSafe
  package_info_plus: ^3.0.3
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  root:
    git:
      url: https://github.com/gokul1630/root
      ref: main
  share_extend: ^2.0.0
  shared_preferences: ^2.1.0
  skeletons: ^0.0.3
  stacked: ^3.2.0
  stacked_generator: ^1.1.0
  stacked_services: ^1.0.0
  stacked_themes: ^0.3.10
  timeago: ^3.3.0
  timezone: ^0.9.0
  url_launcher: ^6.1.10
  wakelock: ^0.6.2
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.14
  pub_release: ^8.0.3
  dio_cache_interceptor: ^3.4.0

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: any
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5  



flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
