name: revanced_manager
description: "Application to use ReVanced on Android."
homepage: https://revanced.app

publish_to: 'none'

version: 1.23.3+101800052

environment:
  sdk: ^3.5.3

dependencies:
  animations: ^2.0.11
  collection: ^1.19.0
  connectivity_plus: ^6.1.3
  device_apps:
    git:
      url: https://github.com/ponces/flutter_plugin_device_apps
      ref: 0609662324b9e00931fccfa87e9e1b00b7610907
  device_info_plus: ^10.1.2
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.0
  dynamic_color: ^1.7.0
  dynamic_themes: ^1.1.0
  expandable: ^5.0.1
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_cache_manager: ^3.3.2
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  injectable: ^2.4.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  language_code: ^0.5.3+2
  logcat:
    git:
      url: https://github.com/BenjaminHalko/logcat
      ref: 4a6d5e0e22292c8eb160cfb9365b9ea29735fd43 # Branch: master
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  root:
    git:
      url: https://github.com/validcube/root
      ref: 68e5678a535a2a3344828a14a39017fa74b9098c # Branch: libsu-521
  screenshot_callback:
    git: # remove once https://github.com/flutter-moum/flutter_screenshot_callback/pull/81 is merged
      url: https://github.com/BenjaminHalko/flutter_screenshot_callback
      ref: 1a1616ac91e16cd1f3dd170a81febf27ffce3587 # Branch: master
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  skeletons:
    git: # remove once https://github.com/badjio/skeletons/pull/11 is merged
      url: https://github.com/Ofceab-Studio/skeletons
      ref: 326fbb4223ac4d8a6301cc2f16b6112ecd308c71 # Branch: master
  slang: ^4.5.0
  slang_flutter: ^4.4.0
  stacked: ^3.4.2
  stacked_generator: ^1.6.0
  stacked_services: ^1.6.0
  synchronized: ^3.3.1
  timeago: ^3.6.1
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  analyzer: ^6.11.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcon
      fonts:
        - asset: fonts/custom-icons.ttf
  assets:
    - assets/i18n/

flutter_localizations:
  sdk: flutter
