name: revanced_manager
description: Patch your favorite apps, right on your device.
homepage: https://github.com/ReVanced/revanced-manager

publish_to: 'none'

version: 1.20.1+101800016

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  collection: ^1.17.0
  connectivity_plus: ^6.0.1
  device_apps:
    git:
      url: https://github.com/ponces/flutter_plugin_device_apps
      ref: 0609662324b9e00931fccfa87e9e1b00b7610907 # Branch: revanced-manager
  device_info_plus: ^9.1.0
  dio: ^5.0.0
  dio_cache_interceptor: ^3.4.0
  dynamic_color: ^1.6.3
  dynamic_themes: ^1.1.0
  expandable: ^5.0.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_background:
    git: # remove once https://github.com/JulianAssmann/flutter_background/pull/79 is merged
      url: https://github.com/BenjaminHalko/flutter_background
      ref: 560d21c4148b53933313573e7eafca0b0eb9aadf # Branch: specify-namespace
  flutter_cache_manager: ^3.3.0
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  language_code: ^0.5.1
  logcat:
    git:
      url: https://github.com/BenjaminHalko/logcat
      ref: 4a6d5e0e22292c8eb160cfb9365b9ea29735fd43 # Branch: master
  package_info_plus: ^6.0.0
  path_provider: ^2.0.14
  permission_handler: ^11.0.1
  root:
    git:
      url: https://github.com/validcube/root
      ref: 68e5678a535a2a3344828a14a39017fa74b9098c # Branch: libsu-521
  screenshot_callback:
    git: # remove once https://github.com/flutter-moum/flutter_screenshot_callback/pull/81 is merged
      url: https://github.com/BenjaminHalko/flutter_screenshot_callback
      ref: 1a1616ac91e16cd1f3dd170a81febf27ffce3587 # Branch: master
  share_plus: ^7.2.1
  shared_preferences: ^2.1.0
  skeletons: ^0.0.3
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  stacked: ^3.2.0
  stacked_generator: ^1.1.0
  stacked_services: ^1.0.0
  synchronized: ^3.1.0
  timeago: ^3.3.0
  timezone: ^0.9.0
  url_launcher: ^6.1.10
  wakelock_plus: ^1.1.3

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: any
  flutter_lints: ^3.0.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcon
      fonts:
        - asset: fonts/custom-icons.ttf
  assets:
    - assets/i18n/

flutter_localizations:
  sdk: flutter
