name: PR Build

on:
  workflow_dispatch:
    inputs:
      flutter-variant:
        required: true
        type: choice
        description: Flutter variant
        default: 'stable'
        options: 
        - stable
        - beta
        - dev
        - master
      app-variant:
        required: true
        type: choice
        description: App variant
        default: 'release'
        options: 
        - release
        - debug
        - profile
      pr-number:
        required: true
        description: PR number (No hashtag)
        
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo clone ReVanced/revanced-manager
          gh pr checkout ${{ inputs.pr-number }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutter-variant }}
          cache: true
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Generate files with Builder
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Build with Flutter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flutter build apk --${{ inputs.app-variant }};
      - name: Set env
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: revanced-manager-${{ env.COMMIT_HASH }}-${{ inputs.pr-number }}-${{ inputs.app-variant }}-${{ inputs.flutter-variant }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          
  notify-pull-request:
    name: Notify Pull Request
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set env
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          if [[ "${{ needs.build.outputs.build_status }}" == "success" ]]; then
            echo "MESSAGE=âœ… Build succeeded!" >> $GITHUB_OUTPUT
          else
            echo "MESSAGE=ðŸš« Build failed!" >> $GITHUB_OUTPUT
          fi
      - name: Comment to Pull Request #${{ inputs.pr-number }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUESTS_WRITE }}
          message: |
            ${{ env.MESSAGE }} @ ${{ env.COMMIT_HASH }}
            
            You can check the details [here](${{ github.event.workflow_run.html_url }}).
  
            - PR: ${{ inputs.pr-number }}
            - App variant: ${{ inputs.app-variant }}
            - Flutter variant: ${{ inputs.flutter-variant }}
