name: Super linter

on:
  pull_request:
    branches:
      - "**"
      
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“œ Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
        
      - name: ğŸ› ï¸ Set up JDK 12
        uses: actions/setup-java@v3
        with:
          java-version: '12'
          distribution: 'zulu'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: ğŸ› ï¸ Set up Flutter
        run: flutter pub get
        
      - name: ğŸ§‘â€ğŸ’» Generate files with Builder
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: ğŸ¤– Task Force Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "github_actions"
