name: Update documentation

on:
  push:
    paths:
      - docs/**

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Dispatch event to documentation repository
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCUMENTATION_REPO_ACCESS_TOKEN  }}
          repository: revanced/revanced-documentation
          event-type: update-documentation
          client-payload: '{"repo": "${{ github.event.repository.name }}", "ref": "${{ github.ref }}"}'
